apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# App label applied to everything for easy selection.
commonLabels:
  app.kubernetes.io/part-of: partnercenterbridge

resources:
  - pvc.yaml
  - api-deployment.yaml
  - api-service.yaml
  - web-deployment.yaml
  - web-service.yaml
  - ingress.yaml

images:
  - name: partnercenterbridge-api
    newTag: latest
  - name: partnercenterbridge-web
    newTag: latest
