// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PartnerCenterBridge.Data;

#nullable disable

namespace PartnerCenterBridge.Data.Sqlite.Migrations
{
    [DbContext(typeof(BridgeDbContext))]
    [Migration("20260927021631_SessionEpoch")]
    partial class SessionEpoch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("ContractDesiredApps", b =>
                {
                    b.Property<Guid>("ContractId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppTemplateId")
                        .HasColumnType("TEXT");

                    b.HasKey("ContractId", "AppTemplateId");

                    b.HasIndex("AppTemplateId");

                    b.ToTable("ContractDesiredApps", (string)null);
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.AppTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ContentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallCommandLine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .HasColumnType("TEXT");

                    b.Property<string>("UninstallCommandLine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("AppTemplates");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("AuthorizationVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InstanceRoles")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWorkbenchOwner")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastLoginAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LockedUntil")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionEpoch")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TotpEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TotpRecoveryCodeHashes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TotpSecretProtected")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OccurredAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("ActorUserId", "OccurredAt");

                    b.HasIndex("TenantId", "OccurredAt");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.ConfigSnapshotRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GitCommitSha")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Imported")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "StartedAt");

                    b.ToTable("ConfigSnapshotRuns");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.ConfigSnapshotSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SectionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "SectionId")
                        .IsUnique();

                    b.ToTable("ConfigSnapshotSections");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.Deployment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppTemplateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignmentIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommittedContentVersionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeployedTemplateVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IntuneAppId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastSyncedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppTemplateId");

                    b.HasIndex("TenantId", "AppTemplateId");

                    b.ToTable("Deployments");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.InstanceAuthorizationState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("InstanceAuthorizationStates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Revision = 1L
                        });
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.McpToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastUsedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("RevokedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("McpTokens");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.PasskeyCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AaGuid")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("CredentialId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long?>("LastUsedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nickname")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<uint>("SignatureCounter")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("UserHandle")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CredentialId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PasskeyCredentials");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.PendingAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DecidedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("DecidedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExecutedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExecutionError")
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviewSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("PendingActions");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.ProvisioningTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultDepartment")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultJobTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseSkuIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpnDomain")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsageLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContractId")
                        .IsUnique();

                    b.ToTable("ProvisioningTemplates");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultDomain")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExchangeOrganization")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExchangeOrganizationVerifiedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GdapRelationshipId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastSeenAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("McpApprovalMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.TenantAccessGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GrantedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GrantedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique();

                    b.ToTable("TenantAccessGrants");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.WorkflowRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("Evidence")
                        .HasColumnType("TEXT");

                    b.Property<string>("Findings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Healthy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Inputs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("TenantId", "StartedAt");

                    b.HasIndex("TenantId", "TargetId", "StartedAt");

                    b.ToTable("WorkflowRuns");
                });

            modelBuilder.Entity("PartnerCenterBridge.Data.SecretRecord", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.ToTable("Secrets");
                });

            modelBuilder.Entity("ContractDesiredApps", b =>
                {
                    b.HasOne("PartnerCenterBridge.Core.Entities.AppTemplate", null)
                        .WithMany()
                        .HasForeignKey("AppTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartnerCenterBridge.Core.Entities.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.AppTemplate", b =>
                {
                    b.HasOne("PartnerCenterBridge.Core.Entities.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsMany("PartnerCenterBridge.Core.Entities.AssignmentSpec", "Assignments", b1 =>
                        {
                            b1.Property<Guid>("AppTemplateId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("GroupDisplayName")
                                .HasColumnType("TEXT");

                            b1.Property<string>("GroupId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Intent")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("TargetType")
                                .HasColumnType("INTEGER");

                            b1.HasKey("AppTemplateId", "Id");

                            b1.ToTable("AppTemplates");

                            b1.ToJson("Assignments");

                            b1.WithOwner()
                                .HasForeignKey("AppTemplateId");
                        });

                    b.OwnsMany("PartnerCenterBridge.Core.Entities.DetectionRule", "DetectionRules", b1 =>
                        {
                            b1.Property<Guid>("AppTemplateId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("Check32BitOn64System")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("EnforceSignatureCheck")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("FileOrKeyName")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Path")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ProductCode")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ProductVersion")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("RunAs32Bit")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ScriptContent")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("AppTemplateId", "Id");

                            b1.ToTable("AppTemplates");

                            b1.ToJson("DetectionRules");

                            b1.WithOwner()
                                .HasForeignKey("AppTemplateId");
                        });

                    b.OwnsOne("PartnerCenterBridge.Core.Entities.Win32ContentInfo", "Content", b1 =>
                        {
                            b1.Property<Guid>("AppTemplateId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("EncryptionKey")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("FileDigest")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("FileDigestAlgorithm")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("InitializationVector")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Mac")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("MacKey")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("ProfileIdentifier")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<long>("Size")
                                .HasColumnType("INTEGER");

                            b1.Property<long>("SizeEncrypted")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("StagedPayloadRef")
                                .HasColumnType("TEXT");

                            b1.HasKey("AppTemplateId");

                            b1.ToTable("AppTemplates");

                            b1.ToJson("Content");

                            b1.WithOwner()
                                .HasForeignKey("AppTemplateId");
                        });

                    b.Navigation("Assignments");

                    b.Navigation("Content");

                    b.Navigation("Contract");

                    b.Navigation("DetectionRules");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.ConfigSnapshotRun", b =>
                {
                    b.HasOne("PartnerCenterBridge.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.ConfigSnapshotSection", b =>
                {
                    b.HasOne("PartnerCenterBridge.Core.Entities.ConfigSnapshotRun", "Run")
                        .WithMany("Sections")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.Contract", b =>
                {
                    b.OwnsOne("PartnerCenterBridge.Core.Entities.OffboardingPolicy", "OffboardingPolicy", b1 =>
                        {
                            b1.Property<Guid>("ContractId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("BlockSignIn")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("ConvertMailboxToShared")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("FollowUpDays")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ForwardTo")
                                .HasColumnType("TEXT");

                            b1.Property<int>("GroupCleanup")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("HideFromGal")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ManagerAccess")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("RemoveLicenses")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("RevokeSessions")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("WipeDevices")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ContractId");

                            b1.ToTable("Contracts");

                            b1.ToJson("OffboardingPolicy");

                            b1.WithOwner()
                                .HasForeignKey("ContractId");
                        });

                    b.Navigation("OffboardingPolicy");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.Deployment", b =>
                {
                    b.HasOne("PartnerCenterBridge.Core.Entities.AppTemplate", "AppTemplate")
                        .WithMany()
                        .HasForeignKey("AppTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartnerCenterBridge.Core.Entities.Tenant", "Tenant")
                        .WithMany("Deployments")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppTemplate");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.McpToken", b =>
                {
                    b.HasOne("PartnerCenterBridge.Core.Entities.AppUser", "User")
                        .WithMany("McpTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.PasskeyCredential", b =>
                {
                    b.HasOne("PartnerCenterBridge.Core.Entities.AppUser", "User")
                        .WithMany("PasskeyCredentials")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.PendingAction", b =>
                {
                    b.HasOne("PartnerCenterBridge.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.ProvisioningTemplate", b =>
                {
                    b.HasOne("PartnerCenterBridge.Core.Entities.Contract", "Contract")
                        .WithOne("ProvisioningTemplate")
                        .HasForeignKey("PartnerCenterBridge.Core.Entities.ProvisioningTemplate", "ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.Tenant", b =>
                {
                    b.HasOne("PartnerCenterBridge.Core.Entities.Contract", "Contract")
                        .WithMany("Tenants")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.TenantAccessGrant", b =>
                {
                    b.HasOne("PartnerCenterBridge.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartnerCenterBridge.Core.Entities.AppUser", "User")
                        .WithMany("TenantAccessGrants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.WorkflowRun", b =>
                {
                    b.HasOne("PartnerCenterBridge.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.AppUser", b =>
                {
                    b.Navigation("McpTokens");

                    b.Navigation("PasskeyCredentials");

                    b.Navigation("TenantAccessGrants");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.ConfigSnapshotRun", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.Contract", b =>
                {
                    b.Navigation("ProvisioningTemplate");

                    b.Navigation("Tenants");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.Tenant", b =>
                {
                    b.Navigation("Deployments");
                });
#pragma warning restore 612, 618
        }
    }
}
