// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PartnerCenterBridge.Data;

#nullable disable

namespace PartnerCenterBridge.Data.Migrations
{
    [DbContext(typeof(BridgeDbContext))]
    [Migration("20260701225444_AddWorkflowRuns")]
    partial class AddWorkflowRuns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.AppTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ContentVersion")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstallCommandLine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Publisher")
                        .HasColumnType("text");

                    b.Property<string>("UninstallCommandLine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("AppTemplates");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.Deployment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("AssignmentIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("CommittedContentVersionId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeployedTemplateVersion")
                        .HasColumnType("integer");

                    b.Property<string>("IntuneAppId")
                        .HasColumnType("text");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AppTemplateId");

                    b.HasIndex("TenantId", "AppTemplateId");

                    b.ToTable("Deployments");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.ProvisioningTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultDepartment")
                        .HasColumnType("text");

                    b.Property<string>("DefaultJobTitle")
                        .HasColumnType("text");

                    b.Property<string>("GroupIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("LicenseSkuIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpnDomain")
                        .HasColumnType("text");

                    b.Property<string>("UsageLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContractId")
                        .IsUnique();

                    b.ToTable("ProvisioningTemplates");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultDomain")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GdapRelationshipId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.WorkflowRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("Findings")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool?>("Healthy")
                        .HasColumnType("boolean");

                    b.Property<string>("Inputs")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("WorkflowId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkflowName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("TenantId", "StartedAt");

                    b.ToTable("WorkflowRuns");
                });

            modelBuilder.Entity("PartnerCenterBridge.Data.SecretRecord", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ProtectedValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Name");

                    b.ToTable("Secrets");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.AppTemplate", b =>
                {
                    b.HasOne("PartnerCenterBridge.Core.Entities.Contract", "Contract")
                        .WithMany("DesiredApps")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsMany("PartnerCenterBridge.Core.Entities.AssignmentSpec", "Assignments", b1 =>
                        {
                            b1.Property<Guid>("AppTemplateId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("GroupDisplayName")
                                .HasColumnType("text");

                            b1.Property<string>("GroupId")
                                .HasColumnType("text");

                            b1.Property<int>("Intent")
                                .HasColumnType("integer");

                            b1.Property<int>("TargetType")
                                .HasColumnType("integer");

                            b1.HasKey("AppTemplateId", "Id");

                            b1.ToTable("AppTemplates");

                            b1.ToJson("Assignments");

                            b1.WithOwner()
                                .HasForeignKey("AppTemplateId");
                        });

                    b.OwnsMany("PartnerCenterBridge.Core.Entities.DetectionRule", "DetectionRules", b1 =>
                        {
                            b1.Property<Guid>("AppTemplateId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<bool>("Check32BitOn64System")
                                .HasColumnType("boolean");

                            b1.Property<bool>("EnforceSignatureCheck")
                                .HasColumnType("boolean");

                            b1.Property<string>("FileOrKeyName")
                                .HasColumnType("text");

                            b1.Property<string>("Path")
                                .HasColumnType("text");

                            b1.Property<string>("ProductCode")
                                .HasColumnType("text");

                            b1.Property<string>("ProductVersion")
                                .HasColumnType("text");

                            b1.Property<bool>("RunAs32Bit")
                                .HasColumnType("boolean");

                            b1.Property<string>("ScriptContent")
                                .HasColumnType("text");

                            b1.Property<int>("Type")
                                .HasColumnType("integer");

                            b1.HasKey("AppTemplateId", "Id");

                            b1.ToTable("AppTemplates");

                            b1.ToJson("DetectionRules");

                            b1.WithOwner()
                                .HasForeignKey("AppTemplateId");
                        });

                    b.OwnsOne("PartnerCenterBridge.Core.Entities.Win32ContentInfo", "Content", b1 =>
                        {
                            b1.Property<Guid>("AppTemplateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("EncryptionKey")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("FileDigest")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("FileDigestAlgorithm")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("InitializationVector")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Mac")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("MacKey")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ProfileIdentifier")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<long>("Size")
                                .HasColumnType("bigint");

                            b1.Property<long>("SizeEncrypted")
                                .HasColumnType("bigint");

                            b1.Property<string>("StagedPayloadRef")
                                .HasColumnType("text");

                            b1.HasKey("AppTemplateId");

                            b1.ToTable("AppTemplates");

                            b1.ToJson("Content");

                            b1.WithOwner()
                                .HasForeignKey("AppTemplateId");
                        });

                    b.Navigation("Assignments");

                    b.Navigation("Content");

                    b.Navigation("Contract");

                    b.Navigation("DetectionRules");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.Deployment", b =>
                {
                    b.HasOne("PartnerCenterBridge.Core.Entities.AppTemplate", "AppTemplate")
                        .WithMany()
                        .HasForeignKey("AppTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartnerCenterBridge.Core.Entities.Tenant", "Tenant")
                        .WithMany("Deployments")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppTemplate");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.ProvisioningTemplate", b =>
                {
                    b.HasOne("PartnerCenterBridge.Core.Entities.Contract", "Contract")
                        .WithOne("ProvisioningTemplate")
                        .HasForeignKey("PartnerCenterBridge.Core.Entities.ProvisioningTemplate", "ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.Tenant", b =>
                {
                    b.HasOne("PartnerCenterBridge.Core.Entities.Contract", "Contract")
                        .WithMany("Tenants")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.WorkflowRun", b =>
                {
                    b.HasOne("PartnerCenterBridge.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.Contract", b =>
                {
                    b.Navigation("DesiredApps");

                    b.Navigation("ProvisioningTemplate");

                    b.Navigation("Tenants");
                });

            modelBuilder.Entity("PartnerCenterBridge.Core.Entities.Tenant", b =>
                {
                    b.Navigation("Deployments");
                });
#pragma warning restore 612, 618
        }
    }
}
